import Foundation
import AppKit

enum ProjectExporter {
    static func markdown(for project: BuildProject) -> String {
        var lines: [String] = []
        lines.append("# \(project.name)")
        lines.append("")
        lines.append("Generated by BuildScout.")
        lines.append("")
        lines.append("## Vehicle")
        lines.append("")
        lines.append("- Candidate: \(project.vehicle.title)")
        lines.append("- Mission: \(project.mission.rawValue)")
        lines.append("- Purchase price: \(money(project.vehicle.price))")
        if !project.vehicle.location.isEmpty {
            lines.append("- Location: \(project.vehicle.location)")
        }
        if let url = project.vehicle.url, !url.isEmpty {
            lines.append("- Listing: \(url)")
        }
        lines.append("")
        lines.append("## Budget")
        lines.append("")
        lines.append("- Target: \(money(project.targetBudget))")
        lines.append("- Current estimate: \(money(project.estimatedTotal))")
        lines.append("- Actual recorded spend: \(money(project.actualSpent))")
        lines.append("- Completion: \(Int(project.completionFraction * 100))%")
        lines.append("")
        lines.append("## Build ledger")
        lines.append("")
        lines.append("| Item | Category | Required | Status | Estimate | Actual |")
        lines.append("| --- | --- | --- | --- | ---: | ---: |")

        for task in project.tasks {
            let actual = task.actualCost.map(money) ?? ""
            lines.append("| \(escape(task.title)) | \(escape(task.category)) | \(task.required ? "Yes" : "No") | \(task.status.rawValue) | \(money(task.estimatedCost)) | \(actual) |")
        }

        if !project.notes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("")
            lines.append("## Notes")
            lines.append("")
            lines.append(project.notes)
        }

        lines.append("")
        lines.append("---")
        lines.append("BuildScout estimates are planning aids. Verify fitment, vehicle condition, title status, safety-critical work, and event rules independently.")

        return lines.joined(separator: "\n")
    }

    @MainActor
    static func saveMarkdown(_ project: BuildProject) {
        let panel = NSSavePanel()
        panel.title = "Export BuildScout build"
        panel.nameFieldStringValue = sanitizedFilename(project.name) + ".md"
        panel.allowedContentTypes = [.plainText]
        panel.canCreateDirectories = true

        guard panel.runModal() == .OK, let url = panel.url else { return }
        try? markdown(for: project).write(to: url, atomically: true, encoding: .utf8)
    }

    @MainActor
    static func saveJSON(_ project: BuildProject) {
        let panel = NSSavePanel()
        panel.title = "Export BuildScout project JSON"
        panel.nameFieldStringValue = sanitizedFilename(project.name) + ".json"
        panel.allowedContentTypes = [.json]
        panel.canCreateDirectories = true

        guard panel.runModal() == .OK, let url = panel.url else { return }

        do {
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            let data = try encoder.encode(project)
            try data.write(to: url, options: [.atomic])
        } catch {
            NSAlert(error: error).runModal()
        }
    }

    private static func money(_ value: Double) -> String {
        value.formatted(.currency(code: "CAD").precision(.fractionLength(0)))
    }

    private static func escape(_ value: String) -> String {
        value.replacingOccurrences(of: "|", with: "\\|")
    }

    private static func sanitizedFilename(_ value: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_ "))
        return value.unicodeScalars
            .map { allowed.contains($0) ? Character(String($0)) : "-" }
            .reduce(into: "") { $0.append($1) }
            .replacingOccurrences(of: " ", with: "-")
    }
}
